### ISSUE TITLE
sort the pdf files, place them into a folder and clean the repo

### ISSUE THREAD

**Issue by ieshreya** [shreyalive/Data-Science#2]

**Comment by DelayCoderz** [comment]
@ieshreya assign me

**Comment by DelayCoderz** [comment]
@ieshreya  #2 I have solved this issue please check it :)

**Comment by ieshreya** [comment]
Thanks @DelayCoderz! 😇

**Comment by DelayCoderz** [comment]
your welcome :)

**Comment by DelayCoderz** [comment]
btw can u approve my pull request ?? cuz this for my hacktoberfest event
